steps:
# - name: 'gcr.io/cloud-builders/gcloud'
#   args:
#   - kms
#   - decrypt
#   - --ciphertext-file=.env.enc
#   - --plaintext-file=.env
#   - --location=global
#   - --keyring=my-project
#   - --key=cloudbuild-env
#install
# - name: 'gcr.io/cloud-builders/npm:node-16.10'
#   args: ['install']

- name: node:16.10
  entrypoint: npm
  args: ['install']

#test
# - name: 'gcr.io/cloud-builders/npm'
#   args: ['run', 'test:unit']

#build    
- name: 'gcr.io/cloud-builders/npm:node-16.10'
  args: ['run', 'build']

#deploy
- name: 'gcr.io/$PROJECT_ID/firebase'
  args: ['deploy'] 

# - name: 'gcr.io/cloud-builders/npm'
#   args: ['run', 'deploy']    